node ('snap-test') {
    parameters {
        booleanParam(defaultValue: false, description: 'Mac job should be triggered', name: 'buildMac')
        booleanParam(defaultValue: false, description: 'Artifacts should be packaged', name: 'packaging')
    }
    stage('dbeaver checkout all repositories') {
        dir('dbeaver-ce') {
            git (
                url: 'https://github.com/dbeaver/dbeaver',
                branch: 'devel'
            )
        }
        
    if ( params.buildMac == true ) {
        build 'Mac_Jobs/dbeaver-ce'
    }
}
}
